gravatar_size: 80
gravatar_small_size: 50
max_length_content: 140
max_length_email: 255
max_length_name: 50
min_length_password: 6
per_page: 5
picture_size_limit: 400
picture_size_mb: 5
time_reset_expired: 2
picture_type_accept: "image/jpeg,image/gif,image/png"
